package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Gun;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUN
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUN
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int insert(Gun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUN
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    Gun selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUN
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    List<Gun> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUN
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int updateByPrimaryKey(Gun record);
}