package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Gunshop;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GunshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUNSHOP
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUNSHOP
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int insert(Gunshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUNSHOP
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    Gunshop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUNSHOP
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    List<Gunshop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GUNSHOP
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    int updateByPrimaryKey(Gunshop record);
}