package lt.vu.mybatis.model;

public class Gun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GUN.ID
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GUN.NAME
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GUN.ACTIONTYPE
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    private String actiontype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GUN.ID
     *
     * @return the value of PUBLIC.GUN.ID
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GUN.ID
     *
     * @param id the value for PUBLIC.GUN.ID
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GUN.NAME
     *
     * @return the value of PUBLIC.GUN.NAME
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GUN.NAME
     *
     * @param name the value for PUBLIC.GUN.NAME
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GUN.ACTIONTYPE
     *
     * @return the value of PUBLIC.GUN.ACTIONTYPE
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public String getActiontype() {
        return actiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GUN.ACTIONTYPE
     *
     * @param actiontype the value for PUBLIC.GUN.ACTIONTYPE
     *
     * @mbg.generated Fri Mar 19 20:59:47 EET 2021
     */
    public void setActiontype(String actiontype) {
        this.actiontype = actiontype;
    }
}